require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "config/routes.rb"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "spec/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Naming/FileName:
  Exclude:
    - "Gemfile"

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": ()
    "%i": ()
    "%q": ()
    "%Q": ()
    "%r": "{}"
    "%s": ()
    "%w": ()
    "%W": ()
    "%x": ()

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 150

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Layout/EndOfLine:
  Enabled: false
