openapi: "3.0.0"
servers:
  - url: https://localhost:4000
info:
  description: ""
  version: "1.0.0"
  title: "cojt_sns_api"
tags:
- name: "user"
  description: "Operations about user"
- name: "Tag"
  description: "タグについての操作"
paths:
  /users:
    post:
      tags:
        - "User"
      summary: "ユーザーの新規作成"
      operationId: "createUser"
      parameters:
        - name: "id"
          in: "query"
          description: "ユーザーid"
          required: true
          schema:
            type: "integer"
        - name: "name"
          in: "query"
          description: "ユーザー名"
          schema:
            type: "string"
        - name: "bio"
          in: "query"
          description: "プロフィール"
          schema:
            type: "string"
        - name: "email"
          in: "query"
          description: "メールアドレス"
          required: true
          schema:
            type: "string"
        - name: "icon_filename"
          in: "query"
          description: "アイコン画像のファイル名"
          schema:
            type: "string"
        - name: "oauth_token"
          in: "query"
          description: "アクセストークン"
          schema:
            type: "string"
        - name: "oauth_token_secret"
          in: "query"
          description: "アクセストークン"
          schema:
            type: "integer"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          description: "Internal Server Error"

  /users/{id}:
    get:
      tags:
        - "User"
      summary: "ユーザー情報の取得"
      operationId: "getUserById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
        "500":
          description: "Internal Server Error"
    put:
      tags:
        - "User"
      security:
      - Bearer: []
      summary: "ユーザー情報の更新"
      operationId: "updateUser"
      parameters:
        - name: "id"
          in: "query"
          description: "ユーザーid"
          required: true
          schema:
            type: "integer"
        - name: "name"
          in: "query"
          description: "ユーザー名"
          schema:
            type: "string"
        - name: "bio"
          in: "query"
          description: "プロフィール"
          schema:
            type: "string"
        - name: "email"
          in: "query"
          description: "メールアドレス"
          schema:
            type: "string"
        - name: "icon_filename"
          in: "query"
          description: "アイコン画像のファイル名"
          schema:
            type: "string"
        - name: "oauth_token"
          in: "query"
          description: "アクセストークン"
          schema:
            type: "string"
        - name: "oauth_token_secret"
          in: "query"
          description: "アクセストークン"
          schema:
            type: "string"
      responses:
        "400":
          description: "Invalid user supplied"
        "403":
          description: "Forbidden"
        "404":
          description: "User not found"
        "500":
          description: "Internal Server Error"
    delete:
      tags:
        - "User"
      security:
      - Bearer: []
      summary: "ユーザーの削除"
      operationId: "deleteUser"
      parameters:
        - name: "id"
          in: "path"
          description: "ユーザーID"
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: "削除完了"
        "403":
          description: "Forbidden"
        "404":
          description: "User not found"
        "500":
          description: "Internal Server Error"
  /users/{id}/tags:
    get:
      tags:
        - "User"
      summary: "特定のユーザー持つタグを取得する"
      operationId: "getUserTags"
      parameters:
        - name: "id"
          in: "path"
          description: "ユーザのID"
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/UserTags'
        "500":
          description: "Internal Server Error"
  /users/{id}/twitter_profile:
    get:
      tags:
        - "User"
      security:
      - Bearer: []
      summary: "特定のユーザーのTwitterプロフィールを取得する"
      operationId: "getUserTags"
      parameters:
        - name: "id"
          in: "path"
          description: "ユーザのID"
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/UserProfile'
        "403":
          description: "Forbidden"
        "404":
          description: "User not found"
        "500":
          description: "Internal Server Error"
  /tags:
    get:
      tags:
      - "Tag"
      summary: "タグを検索する"
      operationId: "searchTag"
      parameters:
        - name: "name"
          in: "query"
          description: "検索name 指定しない場合は全件検索"
          schema:
            type: "string"
        - name: "descendants"
          in: "query"
          description: "返却する子孫の世代数"
          schema:
            type: "integer"
            default: 0
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/TagSearchResult'
        "500":
          description: "Internal Server Error"
    post:
      tags:
      - "Tag"
      security:
      - Bearer: []
      summary: "タグを登録する"
      operationId: "postTag"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/Tag'
        "402":
          description: "認証不正"
        "500":
          description: "Internal Server Error"
  /tags/{id}:
    get:
      tags:
      - "Tag"
      summary: "IDからTagを取得する"
      operationId: "getTag"
      parameters:
        - name: "id"
          in: "path"
          description: "TagのID"
          required: true
          schema:
            type: "integer"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tag"
        "404":
          description: "IDが存在しない"
        "500":
          description: "Internal Server Error"
components:  
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API
  schemas:
    User:
      type: "object"
      properties:
        id: 
          type: "integer"
        name:
          type: "string"
          description: "ユーザー名"
        bio:
          type: "string"
          description: "プロフィール"
        icon_url:
          type: "string"
          description: "プロフィール画像のurl"
    UserTags:
      type: array
      description: "ユーザーに紐づくタグの検索結果(配列)"
      items:
        $ref: '#/components/schemas/Tag'
    UserProfile:
      type: object
      description: "Twitterのユーザープロフィール情報"
      properties:
        id:
          type: "integer"
          example: "1"
        name:
          type: "string"
          description: "Twitterのユーザー名"
          example: "うしゅ"
        bio:
          type: "string"
          description: "TwitterのBIO"
          example: "klis18/AmCr @karahajimaru"
        image_url:
          type: "string"
          description: "TwitterのBIO"
          example: "https://pbs.twimg.com/profile_images/..."
    Tag:
      type: "object"
      properties:
        id:
          type: "integer"
          example: 1
          readOnly: true
        name:
          type: "string"
          description: "タグ名"
          example: "情報メディア創成学類"
        parent_id:
          type: "integer"
          description: "親タグID"
        fullname:
          type: "string"
          description: "フルタグ名"
          example: "筑波大学.情報学群.情報メディア創成学類"
          readOnly: true
    TagSearchResultCandidate:
      type: object
      description: "タグの検索結果1件"
      properties:
        tag:
          $ref: '#/components/schemas/Tag'
        ancestors:
          type: array
          description: "tagの先祖idたち(親から)"
          items:
            $ref: '#/components/schemas/Tag'
        children:
          type: array
          description: "tagの子孫idたち(子から)"
          items:
            $ref: '#/components/schemas/Tag'
    TagSearchResult:
      type: array
      description: "タグの検索結果"
      items:
        $ref: '#/components/schemas/TagSearchResultCandidate'